apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kafka-broker.fullname" . }}
  labels:
    {{- include "kafka-broker.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pv.accessMode }}
  resources:
    requests:
      storage: 1Gi # Request the same storage capacity as the PV
  storageClassName: {{ printf "%s-class-storage" (include "kafka-broker.fullname" .) }} # Match the StorageClass name