apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-broker.fullname" . }}
  labels:
    {{- include "kafka-broker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: internal
      port: 29092
      targetPort: 29092
    - name: controler
      port: 29093
      targetPort: 29093
    - name: jmx
      port: 7072
      targetPort: 7072
    - name: client
      port: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "kafka-broker.selectorLabels" . | nindent 4 }}
