global:
  scrape_interval:     5s
  evaluation_interval: 5s
rule_files:
  - "alert.rules_nodes"
  - "alert.rules_tasks"
  - "alert.rules_service-groups"
scrape_configs:
  - job_name: 'kafka'
    static_configs:
    - targets:
      - 'kafka-broker-0:7072'
      - 'kafka-broker-1:7072'
      labels:
        env: 'dev'