apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv
spec:
  capacity:
    storage: 1Gi # Adjust the storage capacity as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: elastic-storage # Name of the StorageClass
  hostPath:
    path: /run/desktop/mnt/host/e/workspace/event-driven-go/k8s/vol/persistent-elastic-volumn # The path to the directory on the host where the data should be stored
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Request the same storage capacity as the PV
  storageClassName: elastic-storage # Match the StorageClass name
---
apiVersion: v1
kind: Service
metadata:
  name: elastic-service
spec:
  selector:
    app: elastic-service
  ports:
  - name: elastic
    port: 9200
    targetPort: 9200
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic
spec:
  serviceName: "elastic-service"
  selector:
    matchLabels:
      app: elastic-service
  template:
    metadata:
      labels:
        app: elastic-service
    spec:
      initContainers:
      - name: file-permissions
        image: busybox
        command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/']
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elastic-data
        securityContext:
          privileged: true
          runAsUser: 0
      containers:
      - name: elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
        env:
        - name: xpack.security.enabled
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m -XX:+ExitOnOutOfMemoryError"
        - name: discovery.type
          value: single-node
        - name: ELASTIC_PASSWORD
          value: MyPw123
        ports:
        - containerPort: 9200
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 9411
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 30
        #   periodSeconds: 60
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 9411
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 30
        #   periodSeconds: 60
        # resources:
        #   limits:
        #     cpu: 500m
        #     memory: 2Gi
        #   requests:
        #     cpu: 250m
        #     memory: 1Gi
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: elastic-data
      volumes:
        - name: elastic-data
          persistentVolumeClaim:
            claimName: elastic-pvc