apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "18"
    field.cattle.io/publicEndpoints: '[{"addresses":["20.197.101.194"],"port":80,"protocol":"HTTP","serviceName":"tms-prd:tms-notice-ui","ingressName":"tms-prd:ing-tms-prd-notify","hostname":"tmsnotify.central.co.th","path":"/*","allNodes":false},{"addresses":["20.197.101.194"],"port":80,"protocol":"HTTP","serviceName":"tms-prd:tms-notice-service","ingressName":"tms-prd:ing-tms-prd-api","hostname":"tmsnotify.central.co.th","path":"/service/*","allNodes":false},{"addresses":["20.197.101.194"],"port":80,"protocol":"HTTP","serviceName":"tms-prd:tms-notice-service","ingressName":"tms-prd:ing-tms-prd-notify","hostname":"tmsnotify.central.co.th","path":"/api/*","allNodes":false}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"tms-notice-service","namespace":"tms-prd"},"spec":{"selector":{"matchLabels":{"app":"tms-notice-service"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"tms-notice-service"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"Nodepool","operator":"In","values":["stateful"]}]}]}}},"containers":[{"env":[{"name":"TZ","value":"Asia/Bangkok"},{"name":"NODE_ENV","value":"production"},{"name":"MONGODB_URI","value":"mongodb://localhost:27017/db-notice"},{"name":"BASE_URL","value":"https://tmsnotify.central.co.th/api"}],"image":"cgacraksprd.azurecr.io/tms/tms-notice-service:v1.1.18075","livenessProbe":{"httpGet":{"path":"/health","port":3000},"initialDelaySeconds":30,"periodSeconds":60,"timeoutSeconds":30},"name":"tms-notice-service","ports":[{"containerPort":3000,"protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/health","port":3000},"initialDelaySeconds":30,"periodSeconds":60,"timeoutSeconds":30},"resources":{"limits":{"cpu":"100m","memory":"256Mi"},"requests":{"cpu":"50m","memory":"128Mi"}}},{"env":[{"name":"TZ","value":"Asia/Bangkok"},{"name":"NODE_ENV","value":"production"},{"name":"BASE_URL","value":"https://tmsnotify.central.co.th"}],"image":"cgacraksprd.azurecr.io/tms/tms-notice-ui:v1.1.18075","livenessProbe":{"httpGet":{"path":"/","port":8080},"initialDelaySeconds":30,"periodSeconds":60,"timeoutSeconds":30},"name":"tms-notice-ui","ports":[{"containerPort":8080,"protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/","port":8080},"initialDelaySeconds":30,"periodSeconds":60,"timeoutSeconds":30},"resources":{"limits":{"cpu":"100m","memory":"256Mi"},"requests":{"cpu":"50m","memory":"128Mi"}}},{"env":[{"name":"TZ","value":"Asia/Bangkok"},{"name":"NODE_ENV","value":"production"}],"image":"mongo:6.0.6","name":"tms-mongo","ports":[{"containerPort":27017,"protocol":"TCP"}],"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"256Mi"}},"volumeMounts":[{"mountPath":"/data/db","name":"db-mongo"}]}],"tolerations":[{"effect":"NoSchedule","key":"StatefulOnly","operator":"Equal","value":"true"}],"volumes":[{"name":"db-mongo","persistentVolumeClaim":{"claimName":"pv-claim-tms-prd"}}]}}}}
  creationTimestamp: "2022-09-10T12:26:59Z"
  generation: 25
  name: tms-notice-service
  namespace: tms-prd
  resourceVersion: "835720475"
  uid: c68e5500-7b39-414f-904d-c461ba91a7b6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tms-notice-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-10-01T12:28:16Z"
      creationTimestamp: null
      labels:
        app: tms-notice-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: Nodepool
                operator: In
                values:
                - stateful
      containers:
      - env:
        - name: TZ
          value: Asia/Bangkok
        - name: NODE_ENV
          value: production
        - name: MONGODB_URI
          value: mongodb://localhost:27017/db-notice
        - name: BASE_URL
          value: https://tmsnotify.central.co.th/api
        image: cgacraksprd.azurecr.io/tms/tms-notice-service:v1.1.18075
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        name: tms-notice-service
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: TZ
          value: Asia/Bangkok
        - name: NODE_ENV
          value: production
        - name: BASE_URL
          value: https://tmsnotify.central.co.th
        image: cgacraksprd.azurecr.io/tms/tms-notice-ui:v1.1.18075
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        name: tms-notice-ui
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: TZ
          value: Asia/Bangkok
        - name: NODE_ENV
          value: production
        image: mongo:6.0.6
        imagePullPolicy: Always
        name: tms-mongo
        ports:
        - containerPort: 27017
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: db-mongo
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: StatefulOnly
        operator: Equal
        value: "true"
      volumes:
      - name: db-mongo
        persistentVolumeClaim:
          claimName: pv-claim-tms-prd