apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-10-17T10:36:44Z"
  generation: 1
  labels:
    app: kafka-ui
  name: kafka-ui-deployment
  namespace: default
  resourceVersion: "408477"
  uid: 86cd9a65-ff5f-4917-b399-d8ca9b71f2f7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-ui
    spec:
      containers:
      - env:
        - name: KAFKA_CLUSTERS_0_NAME
          value: local
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: ' kafka-broker-0:29092, kafka-broker-0:29092'
        image: provectuslabs/kafka-ui:latest
        imagePullPolicy: Always
        name: kafka-ui
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30