apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 1Gi # Adjust the storage capacity as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana-storage # Name of the StorageClass
  hostPath:
    path: /Users/rosered/Documents/workspace/event-driven-go/k8s/vol/persistent-grafana # The path to the directory on the host where the data should be stored
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Request the same storage capacity as the PV
  storageClassName: grafana-storage # Match the StorageClass name
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-cluster
spec:
  selector:
    app: grafana-cluster
  ports:
  - name: internal
    port: 3000
    targetPort: 3000
  - name: client
    port: 30893
    targetPort: 3000
    nodePort: 30893
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
spec:
  serviceName: "grafana-cluster"
  selector:
    matchLabels:
      app: grafana-cluster
  template:
    metadata:
      labels:
        app: grafana-cluster
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-data
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-pvc