apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-host-pv
spec:
  capacity:
    storage: 1Gi # Adjust the storage capacity as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: k-h-storage # Name of the StorageClass
  hostPath:
    path: /Users/rosered/Documents/workspace/event-driven-go/k8s/vol/persistent-k-h-volumn # The path to the directory on the host where the data should be stored
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-host-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Request the same storage capacity as the PV
  storageClassName: k-h-storage # Match the StorageClass name
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-host-cluster
spec:
  selector:
    app: kafka-host-cluster
  ports:
  - name: internal
    port: 29092
    targetPort: 29092
  - name: jmx
    port: 7072
    targetPort: 7072
    nodePort: 30872
  - name: client
    port: 30881
    targetPort: 30881
    nodePort: 30881
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-host
spec:
  serviceName: "kafka-host-cluster"
  selector:
    matchLabels:
      app: kafka-host-cluster
  template:
    metadata:
      labels:
        component: kafka-host-cluster
        app: kafka-host-cluster
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0 
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
        ports:
        - containerPort: 30881
        - containerPort: 29092
        - containerPort: 7072
        env:
        - name: KAFKA_BROKER_ID
          value: "10"
        - name: KAFKA_LISTENERS
          value: "LISTENER_CONTAINER://0.0.0.0:29092,LISTENER_EXTERNAL://0.0.0.0:30881"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "crs-zookeeper-0.zookeeper-cluster.default.svc.cluster.local:2181"
        - name: ES_JAVA_OPTS
          value: "ES_JAVA_OPTS=-Xms256m -Xmx256m -XX:+ExitOnOutOfMemoryError"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "LISTENER_CONTAINER://kafka-host-cluster:29092,LISTENER_EXTERNAL://localhost:30881"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "LISTENER_CONTAINER:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: LISTENER_CONTAINER

        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"

        - name: KAFKA_OPTS
          value: "-javaagent:/usr/share/jmx_exporter/jar/jmx_prometheus_javaagent-0.19.0.jar=7072:/usr/share/jmx_exporter/kafka-broker.yml"
        resources: {}
        volumeMounts:
          - mountPath: /var/lib/kafka/data
            name: kafka-data
          - name: kafka-jmx
            mountPath: /usr/share/jmx_exporter
          - name: javaagent
            mountPath: /usr/share/jmx_exporter/jar
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-host-pvc
        - name: kafka-jmx
          secret:
            secretName: kafka-jmx-file
        - name: javaagent
          secret:
            secretName: javaagent-file
