apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-0-pv
spec:
  capacity:
    storage: 1Gi # Adjust the storage capacity as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: k-0-storage # Name of the StorageClass
  hostPath:
    path: /Users/rosered/Documents/workspace/event-driven-go/k8s/vol/persistent-k-0-volumn # The path to the directory on the host where the data should be stored
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-0-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Request the same storage capacity as the PV
  storageClassName: k-0-storage # Match the StorageClass name
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-0-cluster
spec:
  selector:
    app: kafka-0-cluster
  ports:
  - name: internal
    port: 29092
    targetPort: 29092
  - name: client
    port: 30882
    targetPort: 30882
    nodePort: 30882
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka-0-cluster"
  selector:
    matchLabels:
      app: kafka-0-cluster
  template:
    metadata:
      labels:
        component: kafka-0-cluster
        app: kafka-0-cluster
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka
        securityContext:
          runAsUser: 0 
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
        ports:
        - containerPort: 30882
        - containerPort: 29092
        env:
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_LISTENERS
          value: "LISTENER_CONTAINER://:29092,LISTENER_EXTERNAL://:30882"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "crs-zookeeper-0.zookeeper-cluster.default.svc.cluster.local:2181"
        - name: ES_JAVA_OPTS
          value: "ES_JAVA_OPTS=-Xms256m -Xmx256m -XX:+ExitOnOutOfMemoryError"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "LISTENER_CONTAINER://kafka-0-cluster:29092,LISTENER_EXTERNAL://localhost:30882"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "LISTENER_CONTAINER:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: LISTENER_CONTAINER
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        resources: {}
        volumeMounts:
          - mountPath: /var/lib/kafka/data
            name: kafka-data
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-0-pvc