apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-0-pv
spec:
  capacity:
    storage: 1Gi # Adjust the storage capacity as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: k-0-storage # Name of the StorageClass
  hostPath:
    path: /Users/rosered/Documents/workspace/event-driven-go/k8s/vol/persistent-k-0-volumn # The path to the directory on the host where the data should be stored
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-0-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Request the same storage capacity as the PV
  storageClassName: k-0-storage # Match the StorageClass name
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-0-cluster
spec:
  selector:
    app: kafka-0-cluster
  ports:
  - name: internal
    port: 29092
    targetPort: 29092
  - name: controler
    port: 29093
    targetPort: 29093
  - name: jmx
    port: 7072
    targetPort: 7072
    nodePort: 30873
  - name: client
    port: 30882
    targetPort: 30882
    nodePort: 30882
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka-0-cluster"
  selector:
    matchLabels:
      app: kafka-0-cluster
  template:
    metadata:
      labels:
        component: kafka-0-cluster
        app: kafka-0-cluster
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0 
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
        ports:
        - containerPort: 30882
        - containerPort: 29092
        - containerPort: 29093
        - containerPort: 7072
        env:
        - name: KAFKA_NODE_ID
          value: "0"
        - name: KAFKA_LISTENERS
          value: "CONTROLLER://:29093,LISTENER_CONTAINER://:29092,LISTENER_EXTERNAL://:30882"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_HEAP_OPTS
          value: "-Xms512M -Xmx512M -XX:+ExitOnOutOfMemoryError"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "LISTENER_CONTAINER://kafka-0-cluster:29092,LISTENER_EXTERNAL://localhost:30882"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,LISTENER_CONTAINER:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: LISTENER_CONTAINER
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "0@kafka-0-cluster:29093,10@kafka-host-cluster:29093"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_LOG_DIRS
          value: "/tmp/kraft-combined-logs"
        - name: CLUSTER_ID
          value: "VE456PBZSdIPphrGgxGtaA=="

        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"

        # - name: KAFKA_KRAFT_MODE
        #   value: "true"
        # - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
        #   value: "false"

        - name: KAFKA_OPTS
          value: "-javaagent:/usr/share/jmx_exporter/jar/jmx_prometheus_javaagent-0.19.0.jar=7072:/usr/share/jmx_exporter/kafka-broker.yml"
        resources: {}
        volumeMounts:
          - mountPath: /var/lib/kafka/data
            name: kafka-data
          - name: kafka-jmx
            mountPath: /usr/share/jmx_exporter
          - name: javaagent
            mountPath: /usr/share/jmx_exporter/jar
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-0-pvc
        - name: kafka-jmx
          secret:
            secretName: kafka-jmx-file
        - name: javaagent
          secret:
            secretName: javaagent-file
