apiVersion: v1
kind: PersistentVolume
metadata:
  name: z-pv
spec:
  capacity:
    storage: 1Gi # Adjust the storage capacity as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: z-local-storage # Name of the StorageClass
  hostPath:
    path: /Users/rosered/Documents/workspace/event-driven-go/k8s/vol/persistent-zookeeper # The path to the directory on the host where the data should be stored
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Request the same storage capacity as the PV
  storageClassName: z-local-storage # Match the StorageClass name
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crs-zookeeper
spec:
  serviceName: "zookeeper-cluster"
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-cluster
  template:
    metadata:
      labels:
        component: zookeeper-cluster
        app: zookeeper-cluster
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        securityContext:
          runAsUser: 0 
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        # lifecycle:
        #   postStart:
        #     exec:
        #       command:
        #         - "sh"
        #         - "-c"
        #         - >
        #           echo $(( $(cat /etc/hosts | grep zookeeper | awk '{print($3)}' | awk '{split($0,array,"-")} END{print array[3]}') + 1 )) > /bitnami/zookeeper/data/myid
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ES_JAVA_OPTS
          value: "ES_JAVA_OPTS=-Xms256m -Xmx256m -XX:+ExitOnOutOfMemoryError"
        - name: ZOO_SERVERS
          value: crs-zookeeper-0.zookeeper-cluster.default.svc.cluster.local:2888:3888
        volumeMounts:
        - name: zookeeper-data
          mountPath: /var/lib/zookeeper
      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: zookeeper-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster
spec:
  selector:
    app: zookeeper-cluster
  ports:
  - name: client
    port: 2181
    targetPort: 2181 
  - name: follower
    port: 2888
    targetPort: 2888 
  - name: leader
    port: 3888
    targetPort: 3888
  clusterIP: None