apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-1
  labels:
    helm.sh/chart: kafka-broker-0.1.0
    app.kubernetes.io/name: kafka-broker-1
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "7.5.1"
    app.kubernetes.io/managed-by: Helm
  namespace: tms-sit
data:
  KAFKA_NODE_ID: "1"
  KAFKA_LISTENERS: "CONTROLLER://:29093,LISTENER_CONTAINER://:29092,LISTENER_EXTERNAL://:30882"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_HEAP_OPTS: "-Xms1280M -Xmx1280M -XX:+ExitOnOutOfMemoryError"
  KAFKA_ADVERTISED_LISTENERS: "LISTENER_CONTAINER://kafka-broker-1:29092,LISTENER_EXTERNAL://localhost:30882"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,LISTENER_CONTAINER:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "LISTENER_CONTAINER"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-broker-1:29093"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  CLUSTER_ID: "VE456PBZSdIPphrGgxGtaA=="
  KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_OPTS: "-javaagent:/usr/share/jmx_exporter/jar/jmx_prometheus_javaagent-0.19.0.jar=7072:/usr/share/jmx_exporter/kafka-broker.yml"
  KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs-v2"
---