apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-env-config
  namespace: tms-sit
data:
  ELASTICSEARCH_SERVICEACCOUNTTOKEN: AAEAAWVsYXN0aWMva2liYW5hL3Rva2VuMTpqUE9qVVlKMFNfLXA5c0NTaHZsTUxR
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: tms-sit
data:
  kibana.yml: |
    server.host: 0.0.0.0
    server.shutdownTimeout: 5s
    elasticsearch.hosts: ['http://localhost:9200']
    monitoring.ui.container.elasticsearch.enabled: true
---
apiVersion: v1
kind: Service
metadata:
  name: elastic-service
  namespace: tms-sit
spec:
  selector:
    app: ek-service
  ports:
  - name: kibana
    port: 5601
    targetPort: 5601
  - name: elastic
    port: 9200
    targetPort: 9200
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic
  namespace: tms-sit
spec:
  serviceName: "ek-service"
  selector:
    matchLabels:
      app: ek-service
  template:
    metadata:
      labels:
        app: ek-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: Nodepool
                operator: In
                values:
                - stateful
      tolerations:
      - effect: NoSchedule
        key: StatefulOnly
        operator: Equal
        value: "true"
      containers:
      - name: elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
        env:
        - name: xpack.security.enabled
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m -XX:+ExitOnOutOfMemoryError"
        - name: discovery.type
          value: single-node
        - name: ELASTIC_PASSWORD
          value: MyPw123
        ports:
        - containerPort: 9200
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 0.5
            memory: 512Mi
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.10.4
        envFrom:
        - configMapRef:
            name: kibana-env-config
        ports:
        - containerPort: 5601
        resources:
          limits:
            cpu: 259m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
          - name: kibana-file
            mountPath: /usr/share/kibana/config
      volumes:
        - name: kibana-file
          configMap:
            name: kibana-config
      