apiVersion: v1
kind: Service
metadata:
  name: grafana-cluster
  namespace: tms-sit
spec:
  selector:
    app: grafana-cluster
  ports:
  - name: internal
    port: 3000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: tms-sit
spec:
  serviceName: "grafana-cluster"
  selector:
    matchLabels:
      app: grafana-cluster
  template:
    metadata:
      labels:
        app: grafana-cluster
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: Nodepool
                operator: In
                values:
                - stateful
      tolerations:
      - effect: NoSchedule
        key: StatefulOnly
        operator: Equal
        value: "true"
      containers:
      - name: grafana
        image: grafana/grafana:10.1.5
        securityContext:
            runAsUser: 0
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 60
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-data
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: pv-claim-tms-sit