apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-deployment
  labels:
    app: kafka-ui
  namespace: tms-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: Nodepool
                operator: In
                values:
                - stateless
      tolerations:
      - effect: NoSchedule
        key: StatelessOnly
        operator: Equal
        value: "true"
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
        - containerPort: 8080
        env:
          - name: KAFKA_CLUSTERS_0_NAME
            value: "local"
          - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
            value: "kafka-broker-1:29092"
          - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
            value: SASL_PLAINTEXT
          - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
            value: PLAIN
          - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG
            value: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="kafka-secret";'
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: tms-dev
spec:
  type: ClusterIP
  selector:
    app: kafka-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080