apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1
  labels:
    helm.sh/chart: kafka-broker-0.1.0
    app.kubernetes.io/name: kafka-broker-1
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "7.5.1"
    app.kubernetes.io/managed-by: Helm
  namespace: tms-sit
spec:
  type: ClusterIP
  ports:
    - name: internal
      port: 29092
      targetPort: 29092
    - name: controler
      port: 29093
      targetPort: 29093
    - name: jmx
      port: 7072
      targetPort: 7072
    - name: client
      port: 30882
      targetPort: 30882
  selector:
    app.kubernetes.io/name: kafka-broker-1
    app.kubernetes.io/instance: release-name